server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /auth/ {
        proxy_pass http://backend:8000/auth/;
    }
    location /schools/ {
        proxy_pass http://backend:8000/schools/;
    }
    location /admin/ {
        proxy_pass http://backend:8000/admin/;
    }
    location /professor/ {
        proxy_pass http://backend:8000/professor/;
    }
    location /notes/ {
        proxy_pass http://backend:8000/notes/;
    }
    location /superadmin/ {
        proxy_pass http://backend:8000/superadmin/;
    }
    location /eleves/ {
        proxy_pass http://backend:8000/eleves/;
    }
    location /bulletin/ {
        proxy_pass http://backend:8000/bulletin/;
    }
}
