/** Palette et styles du modèle BulletinScolaire (Royal Priesthood). */

export const BULLETIN_SCOLAIRE_COLORS = {
  headerBg: '#4a6fa5',
  groupBg: '#4a6fa5',
  subjectBg: '#c8d8e8',
  labelBg: '#4a6fa5',
  borderDark: '#2c3e6b',
  white: '#ffffff',
  black: '#000000',
  lightGray: '#f0f4f8',
  footerBg: '#e8f0f8',
};

const C = BULLETIN_SCOLAIRE_COLORS;

export const bulletinScolaireStyles = {
  page: {
    fontFamily: "'Arial', 'Helvetica', sans-serif",
    fontSize: '10px',
    color: C.black,
    backgroundColor: C.white,
    padding: '12px',
    maxWidth: '900px',
    margin: '0 auto',
    boxSizing: 'border-box',
  },
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '8px',
    gap: '8px',
  },
  headerText: {
    fontSize: '9px',
    lineHeight: '1.4',
    flex: 1,
    textAlign: 'center',
  },
  bold: { fontWeight: 'bold' },
  logoBox: {
    width: '70px',
    height: '70px',
    border: `2px solid ${C.borderDark}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    fontSize: '8px',
    color: '#666',
    borderRadius: '4px',
    overflow: 'hidden',
  },
  logoImg: {
    maxWidth: '100%',
    maxHeight: '100%',
    objectFit: 'contain',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    border: `1.5px solid ${C.borderDark}`,
  },
  titleCell: {
    backgroundColor: C.headerBg,
    color: C.white,
    fontWeight: 'bold',
    fontSize: '13px',
    textAlign: 'center',
    padding: '5px',
    border: `1px solid ${C.borderDark}`,
    letterSpacing: '1px',
  },
  nameRow: {
    backgroundColor: C.headerBg,
    color: C.white,
    fontWeight: 'bold',
    padding: '4px 6px',
    border: `1px solid ${C.borderDark}`,
    fontSize: '11px',
  },
  nameValue: {
    backgroundColor: C.white,
    color: C.black,
    fontWeight: 'bold',
    fontSize: '14px',
    letterSpacing: '0.5px',
    padding: '4px 8px',
    border: `1px solid ${C.borderDark}`,
  },
  infoLabelCell: {
    backgroundColor: C.headerBg,
    color: C.white,
    fontWeight: 'bold',
    padding: '3px 6px',
    border: `1px solid ${C.borderDark}`,
    whiteSpace: 'nowrap',
    fontSize: '9.5px',
  },
  infoValueCell: {
    backgroundColor: C.white,
    padding: '3px 6px',
    border: `1px solid ${C.borderDark}`,
    fontSize: '9.5px',
    fontWeight: 'bold',
  },
  colHeader: {
    backgroundColor: C.labelBg,
    color: C.white,
    fontWeight: 'bold',
    textAlign: 'center',
    padding: '3px 2px',
    border: `1px solid ${C.borderDark}`,
    fontSize: '9px',
  },
  groupHeader: {
    backgroundColor: C.groupBg,
    color: C.white,
    fontWeight: 'bold',
    textAlign: 'center',
    padding: '3px',
    border: `1px solid ${C.borderDark}`,
    fontSize: '10px',
    letterSpacing: '0.5px',
  },
  subjectCell: {
    backgroundColor: C.subjectBg,
    padding: '3px 6px',
    border: `1px solid ${C.borderDark}`,
    fontSize: '9.5px',
    fontWeight: 'bold',
    color: '#1a3a5c',
  },
  dataCell: {
    backgroundColor: C.white,
    textAlign: 'center',
    padding: '3px 2px',
    border: `1px solid ${C.borderDark}`,
    fontSize: '9.5px',
  },
  teacherCell: {
    backgroundColor: C.white,
    textAlign: 'center',
    padding: '3px 4px',
    border: `1px solid ${C.borderDark}`,
    fontSize: '9px',
    fontWeight: 'bold',
  },
  totalRow: {
    backgroundColor: C.headerBg,
    color: C.white,
    fontWeight: 'bold',
    textAlign: 'center',
    padding: '3px',
    border: `1px solid ${C.borderDark}`,
    fontSize: '10px',
  },
  summaryLabelCell: {
    backgroundColor: C.headerBg,
    color: C.white,
    fontWeight: 'bold',
    padding: '4px 6px',
    border: `1px solid ${C.borderDark}`,
    fontSize: '10px',
  },
  summaryValueCell: {
    backgroundColor: C.white,
    fontWeight: 'bold',
    textAlign: 'center',
    padding: '4px 6px',
    border: `1px solid ${C.borderDark}`,
    fontSize: '10px',
  },
  footerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '4px',
    gap: '4px',
  },
  footerCell: {
    flex: 1,
    border: `1px solid ${C.borderDark}`,
    padding: '30px 6px 4px',
    fontSize: '9.5px',
    fontWeight: 'bold',
    minHeight: '50px',
    backgroundColor: C.white,
  },
  nextTerm: {
    marginTop: '6px',
    fontSize: '9.5px',
    fontWeight: 'bold',
  },
};
